server:
  port: 8081
spring:
  application:
    name: client-server
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#打开feign的hystrix功能